### ISSUE TITLE
Does not work with 2017 community edition

### ISSUE THREAD

**Issue by gabortoth-hu** [ricksladkey/SmoothScroll#15]
Install log:

```
2020-01-29 06:35:45 - Microsoft VSIX Installer
2020-01-29 06:35:45 - -------------------------------------------
2020-01-29 06:35:46 - Initializing Install...
2020-01-29 06:35:46 - Extension Details...
2020-01-29 06:35:46 - 	Identifier      : 9ec8f525-55cf-419a-b3df-1436deadbeef
2020-01-29 06:35:46 - 	Name            : Smooth Scroll
2020-01-29 06:35:46 - 	Author          : Rick Sladkey
2020-01-29 06:35:46 - 	Version         : 2.0.2
2020-01-29 06:35:46 - 	Description     : Smooth scrolling for the Visual Studio text editor
2020-01-29 06:35:46 - 	Locale          : en-US
2020-01-29 06:35:46 - 	MoreInfoURL     : https://github.com/ricksladkey/SmoothScroll
2020-01-29 06:35:46 - 	InstalledByMSI  : False
2020-01-29 06:35:46 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2020-01-29 06:35:46 - 
2020-01-29 06:35:46 - 	Supported Products : 
2020-01-29 06:35:46 - 		Microsoft.VisualStudio.Community
2020-01-29 06:35:46 - 			Version : [11.0,17.0)
2020-01-29 06:35:46 - 		Microsoft.VisualStudio.IntegratedShell
2020-01-29 06:35:46 - 			Version : [11.0,17.0)
2020-01-29 06:35:46 - 		Microsoft.VisualStudio.Pro
2020-01-29 06:35:46 - 			Version : [11.0,17.0)
2020-01-29 06:35:46 - 		Microsoft.VisualStudio.Enterprise
2020-01-29 06:35:46 - 			Version : [11.0,17.0)
2020-01-29 06:35:46 - 		AtmelStudio
2020-01-29 06:35:46 - 			Version : [7.0]
2020-01-29 06:35:46 - 
2020-01-29 06:35:46 - 	References      : 
2020-01-29 06:35:46 - 
2020-01-29 06:35:46 - Searching for applicable products...
2020-01-29 06:35:46 - Found installed product - Global Location
2020-01-29 06:35:46 - Found installed product - ssms
2020-01-29 06:35:46 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

VS version:

![image](https://user-images.githubusercontent.com/19283247/73330754-00733580-4262-11ea-8962-840b58ada36b.png)

**Comment by gabortoth-hu** [comment]
I've downloaded `.vsix` from https://marketplace.visualstudio.com earlier, but It works if it is installed from Tools → Extensions and Updates…

**Comment by ricksladkey** [comment]
@gabortoth-hu Thanks for the info. I don't have an explanation for that but I appreciate you reporting the issue. Thanks
